import {
  mdiInformationOutline,
  mdiArrowLeftBoldCircleOutline,
  mdiArrowRightBoldCircleOutline,
  mdiMenuLeft,
  mdiMenuRight,
  mdiChevronUp,
  mdiChevronRight,
  mdiSelectInverse,
  mdiSelect,
  mdiLock,
  mdiLockQuestion,
  mdiAccountMultiple,
  mdiShapeRectanglePlus,
  mdiSquareEditOutline,
  mdiHelpCircle,
  mdiHelpCircleOutline,
  mdiComment,
  mdiGamepadVariant,
  mdiTrophy,
  mdiWindowClose,
  mdiUndo,
  mdiAxe,
  mdiBolt,
  mdiZodiacLibra,
  mdiEmoticonHappyOutline,
  mdiEmoticonSadOutline,
  mdiDeleteOutline,
  mdiWeb,
  mdiFullscreen,
  mdiFullscreenExit,
  mdiAlertCircleOutline,
  mdiStarCircleOutline,
  mdiCheckCircleOutline,
  mdiCheck,
  mdiClose,
  mdiEyeOutline,
  mdiEyeOffOutline,
  mdiAccountGroup,
  mdiTranslateOff,
  mdiTranslate,
  mdiShieldCrownOutline,
  mdiImageAlbum,
  mdiShareVariantOutline,
  mdiDownload,
  mdiContentCopy,
  mdiRefresh,
  mdiMinusCircleOutline,
} from '@mdi/js';

export const ICON = {
  INFO: mdiInformationOutline,
  ARROW_LEFT: mdiArrowLeftBoldCircleOutline,
  ARROW_RIGHT: mdiArrowRightBoldCircleOutline,
  MINI_ARROW_LEFT: mdiMenuLeft,
  MINI_ARROW_RIGHT: mdiMenuRight,
  CHEVRON_UP: mdiChevronUp,
  CHEVRON_RIGHT: mdiChevronRight,
  SELECT_ON: mdiSelectInverse,
  SELECT_OFF: mdiSelect,
  LOCK: mdiLock,
  CODE: mdiLockQuestion,
  USERS: mdiAccountMultiple,
  ADD_TO_COLLECTION: mdiShapeRectanglePlus,
  EDIT_COLLECTION: mdiSquareEditOutline,
  QUESTION: mdiHelpCircle,
  QUESTION_OUTLINE: mdiHelpCircleOutline,
  ANSWER: mdiComment,
  GAME: mdiGamepadVariant,
  ACHIEVEMENT: mdiTrophy,
  X: mdiWindowClose,
  UNDO: mdiUndo,
  GAME_KILLGAME: mdiAxe,
  GAME_PSYCH: mdiBolt,
  GAME_DYLEMATY: mdiZodiacLibra,
  HAPPY: mdiEmoticonHappyOutline,
  SAD: mdiEmoticonSadOutline,
  DELETE: mdiDeleteOutline,
  LANGUAGE: mdiWeb,
  FULLSCREEN_ON: mdiFullscreen,
  FULLSCREEN_OFF: mdiFullscreenExit,
  ERROR: mdiAlertCircleOutline,
  POINTS: mdiStarCircleOutline,
  CHECK: mdiCheckCircleOutline,
  CORRECT: mdiCheck,
  INCORRECT: mdiClose,
  WAKE_LOCK_ON: mdiEyeOutline,
  WAKE_LOCK_OFF: mdiEyeOffOutline,
  TEAM: mdiAccountGroup,
  TRANSLATE_OFF: mdiTranslateOff,
  TRANSLATE_ON: mdiTranslate,
  ADMIN: mdiShieldCrownOutline,
  MEMORIES: mdiImageAlbum,
  SHARE: mdiShareVariantOutline,
  SAVE: mdiDownload,
  COPY: mdiContentCopy,
  REFRESH: mdiRefresh,
  ABANDON: mdiMinusCircleOutline,
} as const;

export type ICON_TYPE = (typeof ICON)[keyof typeof ICON];
