export enum ICON {
  INFO = "mdi-information-outline",
  ARROW_LEFT = "mdi-arrow-left-bold-circle-outline",
  ARROW_RIGHT = "mdi-arrow-right-bold-circle-outline",
  MINI_ARROW_LEFT = "mdi-menu-left",
  MINI_ARROW_RIGHT = "mdi-menu-right",
  CHEVRON_UP = "mdi-chevron-up",
  CHEVRON_RIGHT = "mdi-chevron-right",
  SELECT_ON = "mdi-select-inverse",
  SELECT_OFF = "mdi-select",
  LOCK = "mdi-lock",
  USERS = "mdi-account-multiple",
  ADD_TO_COLLECTION = "mdi-shape-rectangle-plus",
  QUESTION = "mdi-help-circle",
  ANSWER = "mdi-comment",
  GAME = "mdi-gamepad-variant",
  ACHIEVEMENT = "mdi-trophy",
}
