name: FoxTales CI/CD

on:
  push:
    branches:
      - dev

env:
  NODE_VERSION: '20'

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Check linting
        run: npm run lint:check

      - name: Type check
        run: npx vue-tsc
